 # pragma once 
#include <string>
using std::string;
// class City{
// string Algiers="Algiers",
//  Atlanta="Atlanta",
//  Baghdad= "Baghdad",
//     Baghdad="Bangkok",
//         Beijing="Beijing",
//     Bogota="Bogota",
//        BuenosAires= "BuenosAires",
//         Cairo="Cairo",
//         Chennai="Chennai",
//         Chicago="Chicago",
//         Delhi="Delhi",
//         Essen="Essen",
//         HoChiMinhCity="HoChiMinhCity",
//         HongKong="HongKong",
//         Istanbul="Istanbul",
//         Jakarta="Jakarta",
//         Johannesburg="Johannesburg",
//         Karachi="Karachi",
//         Khartoum="Khartoum",
//         Kinshasa="Kinshasa",
//         Kolkata="Kolkata",
//         Lagos="Lagos",
//         Lima="Lima",
//         London="London",
//         LosAngeles="LosAngeles",
//         Madrid="Madrid",
//         Manila="Manila",
//         MexicoCity="MexicoCity",
//         Miami="Miami",
//         Milan="Milan",
//         Montreal="Montreal",
//         Moscow="Moscow",
//         Mumbai="Mumbai",
//         NewYork="NewYork",
//         Osaka="Osaka",
//         Paris="Paris",
//         Riyadh="Riyadh",
//         SanFrancisco="SanFrancisco",
//         Santiago="Santiago",
//         SaoPaulo="SaoPaulo",
//         Seoul="Seoul",
//         Shanghai="Shanghai",
//         StPetersburg="StPetersburg",
//         Sydney="Sydney",
//         Taipei="Taipei",
//         Tehran="Tehran",
//         Tokyo="Tokyo",
//         Washington="Washington";
// };
    
    enum City{
        Algiers,
        Atlanta,
        Baghdad,
        Bangkok,
        Beijing,
        Bogota,
        BuenosAires,
        Cairo,
        Chennai,
        Chicago,
        Delhi,
        Essen,
        HoChiMinhCity,
        HongKong,
        Istanbul,
        Jakarta,
        Johannesburg,
        Karachi,
        Khartoum,
        Kinshasa,
        Kolkata,
        Lagos,
        Lima,
        London,
        LosAngeles,
        Madrid,
        Manila,
        MexicoCity,
        Miami,
        Milan,
        Montreal,
        Moscow,
        Mumbai,
        NewYork,
        Osaka,
        Paris,
        Riyadh,
        SanFrancisco,
        Santiago,
        SaoPaulo,
        Seoul,
        Shanghai,
        StPetersburg,
        Sydney,
        Taipei,
        Tehran,
        Tokyo,
        Washington
    };
    
    
    

    
   


